
-- SELECT defect_lose_power_cuts, defect_lack_power_cuts, defect_power_cuts, product_power, daily_standard_power, defect_lose_ratio FROM iems_shard_kpi_device_01.iems_kpi_inverter_string_day_t_09;
-- SELECT defect_lose_power_cuts, defect_lack_power_cuts, defect_power_cuts, product_power, daily_standard_power, defect_lose_ratio FROM iems_shard_kpi_device_01.iems_kpi_inverter_center_day_t_09;

-- SELECT defect_lose_power_cuts, defect_lack_power_cuts, defect_power_cuts, product_power, daily_standard_power, defect_lose_ratio FROM iems_shard_kpi_device_01.iems_kpi_inverter_string_month_t;
-- SELECT defect_lose_power_cuts, defect_lack_power_cuts, defect_power_cuts, product_power, daily_standard_power, defect_lose_ratio FROM iems_shard_kpi_device_01.iems_kpi_inverter_center_month_t;

-- SELECT defect_lose_power_cuts, defect_lack_power_cuts, defect_power_cuts, product_power, daily_standard_power, defect_lose_ratio FROM iems_shard_kpi_device_01.iems_kpi_inverter_string_year_t;
-- SELECT defect_lose_power_cuts, defect_lack_power_cuts, defect_power_cuts, product_power, daily_standard_power, defect_lose_ratio FROM iems_shard_kpi_device_01.iems_kpi_inverter_center_year_t;


UPDATE iems_shard_kpi_device_01.iems_kpi_inverter_string_day_t_01 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), daily_standard_power = IFNULL(product_power,0) + IFNULL(defect_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/daily_standard_power WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_device_01.iems_kpi_inverter_center_day_t_01 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), daily_standard_power = IFNULL(product_power,0) + IFNULL(defect_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/daily_standard_power WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_device_01.iems_kpi_inverter_string_day_t_02 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), daily_standard_power = IFNULL(product_power,0) + IFNULL(defect_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/daily_standard_power WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_device_01.iems_kpi_inverter_center_day_t_02 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), daily_standard_power = IFNULL(product_power,0) + IFNULL(defect_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/daily_standard_power WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_device_01.iems_kpi_inverter_string_day_t_03 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), daily_standard_power = IFNULL(product_power,0) + IFNULL(defect_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/daily_standard_power WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_device_01.iems_kpi_inverter_center_day_t_03 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), daily_standard_power = IFNULL(product_power,0) + IFNULL(defect_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/daily_standard_power WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_device_01.iems_kpi_inverter_string_day_t_04 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), daily_standard_power = IFNULL(product_power,0) + IFNULL(defect_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/daily_standard_power WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_device_01.iems_kpi_inverter_center_day_t_04 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), daily_standard_power = IFNULL(product_power,0) + IFNULL(defect_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/daily_standard_power WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_device_01.iems_kpi_inverter_string_day_t_05 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), daily_standard_power = IFNULL(product_power,0) + IFNULL(defect_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/daily_standard_power WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_device_01.iems_kpi_inverter_center_day_t_05 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), daily_standard_power = IFNULL(product_power,0) + IFNULL(defect_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/daily_standard_power WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_device_01.iems_kpi_inverter_string_day_t_06 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), daily_standard_power = IFNULL(product_power,0) + IFNULL(defect_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/daily_standard_power WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_device_01.iems_kpi_inverter_center_day_t_06 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), daily_standard_power = IFNULL(product_power,0) + IFNULL(defect_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/daily_standard_power WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_device_01.iems_kpi_inverter_string_day_t_07 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), daily_standard_power = IFNULL(product_power,0) + IFNULL(defect_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/daily_standard_power WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_device_01.iems_kpi_inverter_center_day_t_07 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), daily_standard_power = IFNULL(product_power,0) + IFNULL(defect_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/daily_standard_power WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_device_01.iems_kpi_inverter_string_day_t_08 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), daily_standard_power = IFNULL(product_power,0) + IFNULL(defect_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/daily_standard_power WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_device_01.iems_kpi_inverter_center_day_t_08 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), daily_standard_power = IFNULL(product_power,0) + IFNULL(defect_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/daily_standard_power WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_device_01.iems_kpi_inverter_string_day_t_09 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), daily_standard_power = IFNULL(product_power,0) + IFNULL(defect_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/daily_standard_power WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_device_01.iems_kpi_inverter_center_day_t_09 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), daily_standard_power = IFNULL(product_power,0) + IFNULL(defect_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/daily_standard_power WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_device_01.iems_kpi_inverter_string_day_t_10 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), daily_standard_power = IFNULL(product_power,0) + IFNULL(defect_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/daily_standard_power WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_device_01.iems_kpi_inverter_center_day_t_10 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), daily_standard_power = IFNULL(product_power,0) + IFNULL(defect_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/daily_standard_power WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_device_01.iems_kpi_inverter_string_day_t_11 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), daily_standard_power = IFNULL(product_power,0) + IFNULL(defect_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/daily_standard_power WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_device_01.iems_kpi_inverter_center_day_t_11 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), daily_standard_power = IFNULL(product_power,0) + IFNULL(defect_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/daily_standard_power WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_device_01.iems_kpi_inverter_string_day_t_12 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), daily_standard_power = IFNULL(product_power,0) + IFNULL(defect_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/daily_standard_power WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_device_01.iems_kpi_inverter_center_day_t_12 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), daily_standard_power = IFNULL(product_power,0) + IFNULL(defect_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/daily_standard_power WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;

UPDATE iems_shard_kpi_device_01.iems_kpi_inverter_string_month_t SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), daily_standard_power = IFNULL(product_power,0) + IFNULL(defect_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/daily_standard_power WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_device_01.iems_kpi_inverter_center_month_t SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), daily_standard_power = IFNULL(product_power,0) + IFNULL(defect_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/daily_standard_power WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;

UPDATE iems_shard_kpi_device_01.iems_kpi_inverter_string_year_t SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), daily_standard_power = IFNULL(product_power,0) + IFNULL(defect_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/daily_standard_power WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_device_01.iems_kpi_inverter_center_year_t SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), daily_standard_power = IFNULL(product_power,0) + IFNULL(defect_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/daily_standard_power WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;





-- SELECT defect_lose_power_cuts, defect_lack_power_cuts, defect_power_cuts, inverter_power, defect_lose_ratio, lose_perpower_ratio FROM iems_shard_kpi_station_01.iems_kpi_station_day_t_09;
-- SELECT defect_lose_power_cuts, defect_lack_power_cuts, defect_power_cuts, inverter_power, defect_lose_ratio, lose_perpower_ratio FROM iems_shard_kpi_station_01.iems_kpi_station_month_t;
-- SELECT defect_lose_power_cuts, defect_lack_power_cuts, defect_power_cuts, inverter_power, defect_lose_ratio, lose_perpower_ratio FROM iems_shard_kpi_station_01.iems_kpi_station_year_t;

-- SELECT r.station_code, r.valid_date, r.defect_power_cuts, kpi.s_Id, kpi.collect_time, kpi.defect_power_cuts FROM IEMS.iems_kpi_station_replace_t r, iems_shard_kpi_station_01.iems_kpi_station_month_t kpi WHERE r.date_type = 2 AND r.defect_power_cuts IS NOT NULL AND r.station_code = kpi.s_Id AND r.valid_date = kpi.collect_time;


UPDATE iems_shard_kpi_station_01.iems_kpi_station_day_t_01 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/(IFNULL(inverter_power,0) + IFNULL(defect_power_cuts,0)), lose_perpower_ratio = defect_power_cuts/installed_capacity WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_station_01.iems_kpi_station_day_t_02 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/(IFNULL(inverter_power,0) + IFNULL(defect_power_cuts,0)), lose_perpower_ratio = defect_power_cuts/installed_capacity WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_station_01.iems_kpi_station_day_t_03 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/(IFNULL(inverter_power,0) + IFNULL(defect_power_cuts,0)), lose_perpower_ratio = defect_power_cuts/installed_capacity WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_station_01.iems_kpi_station_day_t_04 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/(IFNULL(inverter_power,0) + IFNULL(defect_power_cuts,0)), lose_perpower_ratio = defect_power_cuts/installed_capacity WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_station_01.iems_kpi_station_day_t_05 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/(IFNULL(inverter_power,0) + IFNULL(defect_power_cuts,0)), lose_perpower_ratio = defect_power_cuts/installed_capacity WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_station_01.iems_kpi_station_day_t_06 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/(IFNULL(inverter_power,0) + IFNULL(defect_power_cuts,0)), lose_perpower_ratio = defect_power_cuts/installed_capacity WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_station_01.iems_kpi_station_day_t_07 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/(IFNULL(inverter_power,0) + IFNULL(defect_power_cuts,0)), lose_perpower_ratio = defect_power_cuts/installed_capacity WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_station_01.iems_kpi_station_day_t_08 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/(IFNULL(inverter_power,0) + IFNULL(defect_power_cuts,0)), lose_perpower_ratio = defect_power_cuts/installed_capacity WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_station_01.iems_kpi_station_day_t_09 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/(IFNULL(inverter_power,0) + IFNULL(defect_power_cuts,0)), lose_perpower_ratio = defect_power_cuts/installed_capacity WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_station_01.iems_kpi_station_day_t_10 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/(IFNULL(inverter_power,0) + IFNULL(defect_power_cuts,0)), lose_perpower_ratio = defect_power_cuts/installed_capacity WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_station_01.iems_kpi_station_day_t_11 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/(IFNULL(inverter_power,0) + IFNULL(defect_power_cuts,0)), lose_perpower_ratio = defect_power_cuts/installed_capacity WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE iems_shard_kpi_station_01.iems_kpi_station_day_t_12 SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0), defect_lose_ratio= defect_power_cuts*100/(IFNULL(inverter_power,0) + IFNULL(defect_power_cuts,0)), lose_perpower_ratio = defect_power_cuts/installed_capacity WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;


-- !!! iems_kpi_station_replace_t

UPDATE iems_shard_kpi_station_01.iems_kpi_station_month_t SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0) WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE IEMS.iems_kpi_station_replace_t r, iems_shard_kpi_station_01.iems_kpi_station_month_t kpi SET kpi.defect_power_cuts = r.defect_power_cuts WHERE r.date_type = 2 AND r.defect_power_cuts IS NOT NULL AND r.station_code = kpi.s_Id AND r.valid_date = kpi.collect_time;
UPDATE iems_shard_kpi_station_01.iems_kpi_station_month_t SET defect_lose_ratio= defect_power_cuts*100/(IFNULL(inverter_power,0) + IFNULL(defect_power_cuts,0)), lose_perpower_ratio = defect_power_cuts/installed_capacity WHERE defect_power_cuts IS NOT NULL;

UPDATE iems_shard_kpi_station_01.iems_kpi_station_year_t SET defect_power_cuts = IFNULL(defect_lose_power_cuts,0) + IFNULL(defect_lack_power_cuts,0) WHERE defect_lose_power_cuts IS NOT NULL OR defect_lack_power_cuts IS NOT NULL;
UPDATE IEMS.iems_kpi_station_replace_t r, iems_shard_kpi_station_01.iems_kpi_station_year_t kpi SET kpi.defect_power_cuts = r.defect_power_cuts WHERE r.date_type = 3 AND r.defect_power_cuts IS NOT NULL AND r.station_code = kpi.s_Id AND r.valid_date = kpi.collect_time;
UPDATE iems_shard_kpi_station_01.iems_kpi_station_year_t SET defect_lose_ratio= defect_power_cuts*100/(IFNULL(inverter_power,0) + IFNULL(defect_power_cuts,0)), lose_perpower_ratio = defect_power_cuts/installed_capacity WHERE defect_power_cuts IS NOT NULL;
